<project
        xmlns="http://maven.apache.org/POM/4.0.0"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>org.sunbird</groupId>
    <artifactId>certification-service</artifactId>
    <version>1.2.0</version>
    <packaging>pom</packaging>
    <name>certification-service</name>
    <properties>
        <project.version>1.0.0-SNAPSHOT</project.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
        <jackson.version>2.14.3</jackson.version>
        <pekko.version>1.0.3</pekko.version>
        <junit.version>4.12</junit.version>

        <version.compiler.plugin>2.3.1</version.compiler.plugin>
        <scoverage.plugin.version>1.1.1</scoverage.plugin.version>
        <slf4j.version>2.0.9</slf4j.version>
        <logback.version>1.4.14</logback.version>

        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <play2.version>3.0.5</play2.version>
        <scala.version>2.13.12</scala.version>
        <scala.major.version>2.13</scala.major.version>
        <powermock.version>1.7.4</powermock.version>
        <httpClient.version>4.5.1</httpClient.version>
        <jacoco.maven.plugin.version>0.8.5</jacoco.maven.plugin.version>
    </properties>

    <modules>
        <module>sb-utils</module>
        <module>cassandra-utils</module>
        <module>sb-es-utils</module>
        <module>all-actors</module>
        <module>service</module>
    </modules>
</project>
