version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk-buster-node-browsers-legacy
    working_directory: ~/project
    steps:
      - checkout
      - restore_cache:
          key: lms-dependency-cache-{{ checksum "pom.xml" }}      
      - run: 
          command: mvn clean install
      - save_cache:
          key: lms-dependency-cache-{{ checksum "pom.xml" }}
          paths: ~/.m2
      - run:
          name: Analyze on SonarCloud
          command: mvn verify sonar:sonar -Dsonar.projectKey=sunbird-lern_certificate-registry -Dsonar.organization=sunbird-lern -Dsonar.host.url=https://sonarcloud.io -Dsonar.coverage.jacoco.xmlReportPaths=/home/circleci/project/service/target/site/jacoco/jacoco.xml,/home/circleci/project/all-actors/target/site/jacoco/jacoco.xml,/home/circleci/project/cassandra-utils/target/site/jacoco/jacoco.xml

workflows:
  version: 2.1
  workflow:
    jobs:
      - build
