## This section has mandatory variables
## You must provide a value for these
## If you don't provide a value for these variables, the chart installation will not proceed

## The domain name or Public IP address
## The domain name should start with http or https
