## This section has mandatory variables
## You must provide a value for these
## If you don't provide a value for these variables, the chart installation will not proceed

## The domain name or Public IP address
## The domain name should start with http or https
## For example https://example.com


## This section has variables with default values
## These are standard defaults that work well
## You can override these if you have a use case for it
cert_service_base_url: http://cert-service.lern.svc.cluster.local
rc_entity: TrainingCertificate
registry_credential_service_base_url: http://registry-service.lern.svc.cluster.local:8081
sunbird_cassandra_consistency_level: quorum
sunbird_cassandra_host: cassandra.lern.svc.cluster.local
sunbird_cassandra_keyspace: sunbird
sunbird_cassandra_password: password
sunbird_cassandra_port: "9042"
sunbird_cassandra_username: cassandra
sunbird_es_host: http://elasticsearch.lern.svc.cluster.local
sunbird_es_port: "9300"

external_configmaps:
  common_opa_policies:
    name: common-opa-policies
  common_opa_policies_keys:
    name: common-opa-policies-public-keys  
  access_public_keys:
    name: user-access-keys-public
## Variables with empty values
## The value for these variables will be contstucted using other variables
## If you provide a value to the variable, then that will take the highest precedence
## It's recommended to leave these blanks unless you have a strong use case to override them

## Set this value to true when developing the chart
local_chart_development: true


## This section has other kubernetes variables
## These are standard defaults that work well
## You can override these if you have a use case for it
image:
  registry: docker.io
  repository: ssksanthosh/cert_registry_service
  tag: release-5.0.0

replicaCount: 1

strategy:
  maxSurge: 25%
  maxUnavailable: 25%

imagePullSecrets: ""

javaOptions: -Xmx600m

resources:
  requests:
    cpu: 100m
    memory: 100M
  limits:
    cpu: 1
    memory: 1G

port: 9000

targetPort: 9000

livenessProbe:
  failureThreshold: 2
  httpGet:
      path: /service/health
      port: 9000
  initialDelaySeconds: 15
  periodSeconds: 15
  timeoutSeconds: 5

readinessProbe:
  failureThreshold: 2
  httpGet:
      path: /service/health
      port: 9000
  initialDelaySeconds: 15
  periodSeconds: 15
  timeoutSeconds: 5

opa_sidecar: true

envoy_livenessProbe:
  failureThreshold: 2
  httpGet:
      path: /ready
      port: 10000
      scheme: HTTP
  initialDelaySeconds: 5
  periodSeconds: 15
  timeoutSeconds: 5

envoy_readinessProbe:
  failureThreshold: 2
  httpGet:
      path: /ready
      port: 10000
      scheme: HTTP
  initialDelaySeconds: 5
  periodSeconds: 15
  timeoutSeconds: 5

opa_livenessProbe:
  failureThreshold: 2
  httpGet:
      path: /health?plugins
      port: 8282
      scheme: HTTP
  initialDelaySeconds: 5
  periodSeconds: 15
  timeoutSeconds: 5

opa_readinessProbe:
  failureThreshold: 2
  httpGet:
      path: /health?bundle=true
      port: 8282
      scheme: HTTP
  initialDelaySeconds: 5
  periodSeconds: 15
  timeoutSeconds: 5

envoy_resources:
  requests:
    cpu: 100m
    memory: 100M
  limits:
    cpu: 1
    memory: 1G

opa_resources:
  requests:
    cpu: 100m
    memory: 100M
  limits:
    cpu: 1
    memory: 1G

initcontainer_resources:
  requests:
    cpu: 100m
    memory: 100M
  limits:
    cpu: 100m
    memory: 100M

## dependency charts - change enabled: true  if you plan to use standalone chart only
common_opa_policies:
  enabled: false
